<?php

namespace EolabsIo\AmazonMwsResponseParser\Parsers;

use EolabsIo\AmazonMwsResponseParser\Parsers\ListMarketplaceParticipationsResponseParser;

class ListMarketplaceParticipationsByNextTokenResponseParser extends ListMarketplaceParticipationsResponseParser
{

}